version: "3.7"

services:
  nginx:
    image: nginx
    volumes:
      - "./build:/usr/share/nginx/html"
      - "./default.conf:/etc/nginx/conf.d/default.conf"
      - "/etc/letsencrypt/live/comoaprendiabailar.com:/etc/letsencrypt/live/comoaprendiabailar.com"
    ports:
      - "80:80"
      - "443:443"
